<a href="https://colab.research.google.com/github/SOM2003DATT/anonymous/blob/main/diplab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np


In [3]:
L=[1,2,3,4]
arr=np.array(L)
print(L)
print(arr) 
print(type(L))
print(type(arr))

[1, 2, 3, 4]
[1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>


In [4]:
L1=[[1,2,3],[4,5,6]]
arr1=np.array(L1)
print(L1)
print('-------')
print(arr1)


[[1, 2, 3], [4, 5, 6]]
-------
[[1 2 3]
 [4 5 6]]


In [5]:
L2=[i for i in range(500,601)]
arr2=np.array(L2)
print(arr2)

[500 501 502 503 504 505 506 507 508 509 510 511 512 513 514 515 516 517
 518 519 520 521 522 523 524 525 526 527 528 529 530 531 532 533 534 535
 536 537 538 539 540 541 542 543 544 545 546 547 548 549 550 551 552 553
 554 555 556 557 558 559 560 561 562 563 564 565 566 567 568 569 570 571
 572 573 574 575 576 577 578 579 580 581 582 583 584 585 586 587 588 589
 590 591 592 593 594 595 596 597 598 599 600]


In [7]:
L4 = np.arange(200,300).reshape(2,2,5,5)
print(L3)

NameError: ignored

In [8]:
array1 = np.random.rand(200)
array2 = np.random.rand(300)

test = np.hstack((array1,array2))
test.shape
(500,)

(500,)

In [10]:
import numpy as np


In [12]:
np.arange(200*300).reshape(200,300)

array([[    0,     1,     2, ...,   297,   298,   299],
       [  300,   301,   302, ...,   597,   598,   599],
       [  600,   601,   602, ...,   897,   898,   899],
       ...,
       [59100, 59101, 59102, ..., 59397, 59398, 59399],
       [59400, 59401, 59402, ..., 59697, 59698, 59699],
       [59700, 59701, 59702, ..., 59997, 59998, 59999]])

In [20]:
np.zeros((2,3,4),int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [21]:
np.ones((3,5,6),int)

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]])